Fractal
nawhas/nawhas-app pull request #18
Opened 2017-08-15 22:02 UTC by shea786

2017-08-17 23:26 UTC, szainmehdi requested changes
Also remember to update the `RecitersApiTest`

2017-08-17 23:26 UTC, szainmehdi commented on app/Transformers/AlbumsTransformer.php
> +class AlbumsTransformer extends TransformerAbstract
Each of these `Transformer` classes should be singular. It's only job is to transform a single entity. 

`AlbumTransformer` for example.

2017-08-17 23:26 UTC, szainmehdi commented on app/Transformers/TracksTransformer.php
> +            'link' => $track->mp3_link,
This should be `audio_file_url` maybe?

2017-08-17 23:26 UTC, szainmehdi commented on app/Transformers/TracksTransformer.php
> +            'file' => $track->file_path,
What is `file_path`?

2017-08-18 19:32 UTC, shea786 commented on app/Transformers/TracksTransformer.php
> +            'file' => $track->file_path,
so currently we have two options, either upload a mp3 or specify a url
file_path is the path to the uploaded file
mp3_link is the link to the external mp3 file

i dont know if we want to change this in the database level and change the names

2017-09-03 22:07 UTC, szainmehdi approved these changes

2017-09-03 22:11 UTC, merged